name: CI/CD - Deploy Strapi on ECS Fargate with Terraform

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  TF_VAR_AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: Build Docker Image, Push to ECR & Deploy Infra with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          IMAGE_TAG="${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          docker build -t "$IMAGE_TAG" -f docker/Dockerfile .
          echo "Built image: $IMAGE_TAG"

      - name: Push Docker Image to ECR
        run: |
          IMAGE_TAG="${ECR_REGISTRY}/${ECR_REPOSITORY}:latest"
          docker push "$IMAGE_TAG"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Output Public ALB URL
        id: alb_url
        run: |
          ALB_URL=$(terraform output -raw alb_public_url)
          echo "ALB_URL=$ALB_URL" >> $GITHUB_ENV

      - name: Notify Deployment Success
        run: |
          echo "Strapi is now deployed at: $ALB_URL"
